'''
Main script to be executed.
Includes all necessary Snakefiles needed
to execute the workflow.
'''

configfile: "../config/paths.yaml"
configfile: "../config/parameters.yaml"

SAMPLES = [sample.split(".")[0] for sample in os.listdir(config["sample_dir"])]

rule all:
    input:
        pdf=expand("{results_dir}variant_evaluation/{chr_id}.pdf",results_dir=config["results_dir"], chr_id=config["chromosome_name"]),
        vcf_files=expand("{results_dir}variants/{sample}.vcf", sample=SAMPLES, results_dir=config["results_dir"])

include: "rules/functions.smk"
include: "rules/pre_processing.smk"
include: "rules/genome_indexing.smk"
include: "rules/alignment.smk"
include: "rules/post_processing.smk"
include: "rules/variant_calling.smk"
include: "rules/variant_evaluation.smk"
